### ISSUE TITLE
tonights test

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#130]
we just merged and tested tonight. Problems were:

 - False positive on "IsUserAwakeBeforeShutdown" 
 - Calls stop, when all alerts ach'd, but do not restart after some time.

I was doing some refactoring, so instead of fixing the upper problem in the master, I tried my refactored version. It had the same problem as the master, but I found it quickly and fixed it. 

2nd problem I did not yet look at, but I know what's wrong. 
I go to be now.

**Comment by MaxNoe** [comment]
This is fixed I think?
