### ISSUE TITLE
Website did not show alerts for shifter

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#136]
This morning the shifthelper called a testshifter who had the master branch running simulatneosly. 
So incoming calls cannot be distinguished. He looked at the shifthelper webinterface and no alerts were shown. Even after refreshing the page, no alerts were shown.

I wasn't able to reproduce this later. Not sure how to hunt this bug down.
We have to see tomorrow morning how it behaves.

**Comment by MaxNoe** [comment]
Which alerts where not shown? The website currently shows 4 shifter not awake alerts. These are also the only ones in the database for today.

**Comment by dneise** [comment]
Exactly those were not shown, if I remember correctly. As I said: I was not able to reproduce this, i.e. for me everything was shown right away correctly.

**Comment by MaxNoe** [comment]
I will close this for now because it did not show up again and might just have been a call of the old shifthelper.
