### ISSUE TITLE
check interval 2 min

### ISSUE THREAD

**Issue by dadorner** [fact-project/shifthelper#194]
from what I remember, Adrian decided in the last telcon before Christmas that the interval in which the status of the system is checked should be changed from 5 to 2 minutes

**Comment by dneise** [comment]
yes ... it was not forgotten .. just after the night where the shifthelper did not call you at all (you remember?) we agreed, that we must under no circumstances put untested software into production. 

We have a hard time finding time for testing (volunteers?) ... so new features (even if implementing them means to change a single `300` to `120`) take their time.
