### ISSUE TITLE
One Flare - One Call

### ISSUE THREAD

**Issue by madoee** [fact-project/shifthelper#198]
Currently, Shifthelper repeatedly calls once the QLA has yielded Flare Alert limits, even if it is the same flare. This results in several calls for the same flare.

**Comment by MaxNoe** [comment]
It shouldn't do that allready. It should only call again for the same source if the rate is higher than before. Was that the case?

**Comment by dneise** [comment]
Thanks for reporting @madoee.
@MaxNoe  have a look here https://ihp-pc41.ethz.ch/ then you see what is the case and what not.
![2017-01-09-111618_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8200858/21763235/2923775c-d65d-11e6-9177-5210b03c8539.png)

**Comment by MaxNoe** [comment]
Mmh, that's strange. I will investigate

**Comment by MaxNoe** [comment]
Fixed by #211
