### ISSUE TITLE
Telegram QLA bot not working

### ISSUE THREAD

**Issue by bowe46** [fact-project/shifthelper#206]
Even if Telegram is properly working for FACT bot, it seems that QLA bot doesn't work correctly. When sending the /qla command, nothing is given as a result.

**Comment by MaxNoe** [comment]
Hi Matteo,

the machine on which the qla bot was running is currently being physically moved, hence the downtime.

Sorry :)

But you will receive QLA Plots via the FACT bot in case of a flare.
