### ISSUE TITLE
Shifter Webinterface is filled with traceback errors e.g.   `RelativeCameraTemperatureCheck `...

### ISSUE THREAD

**Issue by lestrix** [fact-project/shifthelper#208]
stacking up over daytime.  

`Exception while running check. Traceback: Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn (self.host, self.port), self.timeout, **extra_kw) File "/opt/conda/lib/python3.5/site-packages/requests/package`
....
http://www.imageloader.de/?img=121486194544.png

**Comment by MaxNoe** [comment]
Fixed by updateting to new custos version
