### ISSUE TITLE
Shifthelper call - Reading out problem 

### ISSUE THREAD

**Issue by madoee** [fact-project/shifthelper#214]
During my shift in January, the shifthelper would call and read out the error message displayed on the shifthelper webinterface. During the past two nights, the shifthelper called me and hung up immediately once I accepted the call. The calls were dummy alerts, a warning about high currents in the G-APDs, and a "Shifter is not awake 20 mins before shutdown" alert.

**Comment by MaxNoe** [comment]
We changed it to save money. 

You should also not accept the calls anymore.
