### ISSUE TITLE
Update shifter phonebook regularly

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#215]
Right now, the phonebook is only created once at startup, it should update regularly, like every 5 minutes or so, so that shifters can change their phonenumbers without having to restart the helper

**Comment by MaxNoe** [comment]
The phonebook will be updated every ten minutes from now on. Because we clone the db every 5 minutes, the time between a change of the phone number and it taking effect fpr the shifthelper should therefor be 15 minutes max.

**Comment by dneise** [comment]
should this info find its way into the shift manual? Not really ... too much detail obscuring the important stuff in the shift manual, right?
