### ISSUE TITLE
Additional "user" log stream

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#216]
We need to create the logstream I talked about here:
https://github.com/fact-project/shifthelper_webinterface/issues/23

**Comment by dneise** [comment]
Regarding privacy:

When logging who the shifthelper is trying to call. We will print the ldap usernames here, not the real names and not the telephone numbers.

**Comment by MaxNoe** [comment]
This is implemented in https://github.com/fact-project/shifthelper_webinterface/pull/24 and requires the user to be logged in.
