### ISSUE TITLE
Check Trigger Rate

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#22]
Originally reported by: **Maximilian Nöthe (Bitbucket: [MaxNoe](http://bitbucket.org/MaxNoe), GitHub: [MaxNoe](http://github.com/MaxNoe))**

----------------------------------------

We should also check if the trigger rates are ok.

I just had the case, where the trigger rates where at zero for a longer time,
no idea why but restarting Main.js helped.

However, this should be a bit more elaborate right? The shifter should not be contacted if it is just a FAD loss with automatic reconnect.

----------------------------------------
- Bitbucket: https://bitbucket.org/dneise/fact_shift_helper/issue/22

**Comment by dneise** [comment]
This is included in #91
