### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mackaiver** [fact-project/shifthelper#235]
Hello, 
after logging in and clicking on the test telegram button I got an internal server error response.

https://shifthelper.app.tu-dortmund.de/testTelegram

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by dneise** [comment]
What's up with this issue? Was it somehow solved?

**Comment by MaxNoe** [comment]
This is an issue for the webinterface and I think it was solved through introduction `pool_recycle` for the db connection
