### ISSUE TITLE
We still have the FlareAlertCheck in the code, but do not need it anymore

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#264]
It is always ugly to throw away stuff, which cost much time to develop, and is not used anymore. 
Still should we get rid of this?

https://github.com/fact-project/shifthelper/blob/6b841be6f28fb4cac2cb56b6758cfbfd06c55a8b/shifthelper/checks.py#L49

**Comment by dneise** [comment]
I think this question goes mostly to @MaxNoe 

It is not urgent ... more like a reminder to ourselves

**Comment by MaxNoe** [comment]
> It is always ugly to throw away stuff, which cost much time to develop, and is not used anymore.

I really, really love throwing away unused code. Especially if it's mine.

**Comment by MaxNoe** [comment]
I removed it in #267
