### ISSUE TITLE
Redundant shift_helper process

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#53]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

The task to solve is:

What if there the shift_helper instance running on the shifters box has not network?

It will neither be able to check the status of the telescope, nor will it be able to wake the shifter and tell her about it.

---
- Bitbucket: https://bitbucket.org/dneise/fact_shift_helper/issue/53

**Comment by dneise** [comment]
Have a look at these pics:

---

This is what we have at the moment

![20160208_081726](https://cloud.githubusercontent.com/assets/8200858/12892123/e9556c5a-ce8a-11e5-9e93-005ae3a37b4e.jpg)


Here we put a seconds helper, on a different machine. 
 * It does not talk to the 1st helper
 * does only call if "value > limit" for 10minutes persistently.
 * does not call for Flare alerts

![20160208_083054](https://cloud.githubusercontent.com/assets/8200858/12892127/ebf11fae-ce8a-11e5-806a-0eeaa1cff581.jpg)

Here we add a 2nd shifter:

 * only called from 1st helper, if constantly "value > limit" for 15min
 * only called from 2nd helper, if constantly "value > limit" for 20min

![20160208_090238](https://cloud.githubusercontent.com/assets/8200858/12892207/5328e59e-ce8b-11e5-9f9a-a6978e7d37b3.jpg)


Here we add the possibility for the 1st shifter to tell both shift_helpers, who is on shift tonight.
And also prevent both helpers from calling anybody.

![20160208_173426](https://cloud.githubusercontent.com/assets/8200858/12892257/a131a3fc-ce8b-11e5-9189-09e01e8130aa.jpg)

**Comment by dneise** [comment]
Not gonna fly like this
