### ISSUE TITLE
Do we wake up the shifter, if mysql server (for QLA) is not reachable for a small amount of time?

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#56]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

At the moment our policy is: 

If the shift_helper has a problem. like it cannot see smartfact, or cannot reach the mysql server for the QLA, it throws up. And this results in a call to the shifter. Which hopefully finally results in a message to the developers, so we can try to fix it.

I think that's fine for now.

But for the future, what do you think about relaxing this a little bit like:

If the helper does not see something for O(30min) this is totally fine, since a shifter watching Starship Enterprise Episodes, also would not check the telescope more often than every 30min or so...

I would still log this, and inform the developers about it, but not wake the shifter unless the connection is down for ... well a long time.

---
- Bitbucket: https://bitbucket.org/dneise/fact_shift_helper/issue/56

**Comment by dneise** [comment]
see here for how to implement multiple retries with increasing delays.

https://github.com/kennethreitz/requests/issues/2682

**Comment by MaxNoe** [comment]
Fixed by retrying
