### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#59]
```
19:53:40 - WARNING - py.warnings | 
/home/dneise/anaconda3/lib/python3.5/site-packages/
fact_shift_helper/checks/qla.py:121: 
FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
```

[newlines by me.]

**Comment by MaxNoe** [comment]
Yes. `sort` got deprecated in `pandas0.17.0`. But using `sort_values` breaks compatibility with `0.16`.

Do we want to force `0.17`. I didn't want to do something like:
```
try:
    df.sort_values()
except:
    df.sort()
```

I would propose to wait until `0.18` comes out, so that we stay compatible to the last two versions.

**Comment by dneise** [comment]
perfect.

**Comment by dneise** [comment]
0.18 is out, is this solved now?
