### ISSUE TITLE
QLAs do not agree

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#61]
Please have a look at these two QLA results. 
They do not agree. 

I think it is critical for our tool, to have them agreeing. I think Max N. already knows kind of the reason for this. So maybe the question is: *Do we agree, that having the same QLA results is critical for the success of the shifthelper?*

![screenshot from 2016-02-03 08-22-44](https://cloud.githubusercontent.com/assets/8200858/12775616/aab11f7e-ca4f-11e5-971f-78ef084e3b8d.png)
![qla_2016-02-03_08-22-55](https://cloud.githubusercontent.com/assets/8200858/12775620/abeb9a54-ca4f-11e5-9772-d0f00eb9af16.jpg)

**Comment by MaxNoe** [comment]
Yes, I agree it's critical. The binslides that are there match, right? So we are discarding  bins which daniela keeps. I have to check her code again.

**Comment by MaxNoe** [comment]
I removed the cut, that threw away bins that had less than 90 % fOntime of the target binning.
The result is:
![qla2016-02-03_10-39-40](https://cloud.githubusercontent.com/assets/5488440/12778347/8e7c96ae-ca62-11e5-91af-6665301ad39a.jpg)

**Comment by MaxNoe** [comment]
I think I got it. I replaced a `>=` with a `>` and check only the last bin for the ontime.
![qla2016-02-03_10-39-40](https://cloud.githubusercontent.com/assets/5488440/12780035/e8f7634e-ca6b-11e5-992a-69ed1dd4143c.jpg)

**Comment by MaxNoe** [comment]
This was close via #62 .
