### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#70]
From #69 and others I learned that `shifthelper` was not the smartest choice for a name. 

The task of the program is (greatly shortened):

**Alert the shifter, when manual interaction is definitely needed.**

But `shifthelper` implies a great deal of other tasks, which this program could do, but imho shouldn't do.
Maybe `shifthelper` is a good name for a suite of helpful programs for the shifters.

**Comment by MaxNoe** [comment]
- SECFAN   Security and Flare Alert Notifier

**Comment by MaxNoe** [comment]
* SELINAS **Se**curity **Li**mit **No**tification **A**lert **S**ystem

**Comment by dneise** [comment]
Caller.

**Comment by MaxNoe** [comment]
MoFa - Monitor Fact

**Comment by MaxNoe** [comment]
PLIFAC - Python Limits and Flare Alert Caller

**Comment by mackaiver** [comment]
AASSS - Automatic Alert System for Sleeping Shifters

**Comment by MaxNoe** [comment]
:+1:

**Comment by dneise** [comment]
This was closed, since people are accustomed to the name. And I cannot stop using it.
