### ISSUE TITLE
Problems downloading config file

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#71]
Anton had difficulties downloading the config file.

He was able to download manually using the browser and copy it to `$HOME/.shifthelper`. The process was much delayed since he also had an old version of the shift_helper still lying around. After we found that out and uninstalled the old version, it seemed to work nicely. 

I have no idea, why the shifthelper was unable to download the file for him, but I fear it has something to do with this funny caching we experienced already.

**Comment by MaxNoe** [comment]
Not a problem anymore.
