### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#72]
In case we think shifthelper should also work on windows,

maybe the 'windows' branch is a starting point.
I wonder if than branch would still run on Linux... have no machine here to test... might do it tomorrow.

https://github.com/fact-project/shifthelper/tree/windows

**Comment by dneise** [comment]
The only reason for the necessity of the windows branch is our use of blessings, if I'm not mistaken.
Since in the future we do not expect users to actually look at the screen while shifthelper is running. We could drop the use of blessings entirely.

On the other hand, since in the future we plan to run it on a server as opposed to a users pc, there is no need for windows support.

**Comment by MaxNoe** [comment]
Not a problem anymore with the centralised version
