### ISSUE TITLE
(possible) bug in qla plot

### ISSUE THREAD

**Issue by Solarer** [fact-project/shifthelper#81]
Today I switched from old version 0.3.4 to 0.6.1 
Max sent me the 0.6.1.ini file that contains new flare limits (60 instead of 45) and I placed it into the shifthelper folder. After restarting shifthelper I got called, because Mrk421 exceeded the 60 evts/h trigger tonight and the plot looked good.

However, if I send /qla to the telegram bot, I receive a different plot where the limit is still at 45. See attached files below.
Removing the old config files of 0.3.4 and 0.5.0 did not solve the issue.

![photo_2016-06-10_01-26-54](https://cloud.githubusercontent.com/assets/2805109/15949803/7ba52f80-2eaa-11e6-89bb-aacaf0b45304.jpg)
![photo_2016-06-10_01-27-04](https://cloud.githubusercontent.com/assets/2805109/15949804/7ba6fe82-2eaa-11e6-81ad-e651dbbb4a34.jpg)

**Comment by MaxNoe** [comment]
Just an out-of-date version of the shifthelper on the computer the bot is running on.
