### ISSUE TITLE
No notification despite main.js crash

### ISSUE THREAD

**Issue by mackaiver** [fact-project/shifthelper#85]
Hello.

I had some trouble during the night shift. I was not notified of a main.js crash. Maybe connection problems to the island. I attached the logfile. 

[shifthelper_2016-09-09.txt](https://github.com/fact-project/shifthelper/files/465274/shifthelper_2016-09-09.txt)

**Comment by MaxNoe** [comment]
I think I identified the Problem. You had no internetconnection → smartfact check timeout →twilio timeout.

The twilio timeout is not catched and not logged. I wonder why this did not occure earlier...
