### ISSUE TITLE
automatic check of ratescan

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#9]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

----------------------------------------

As discussed today, shifters should check the ratescan and in case it is 'bad', another ratescan should be taken.

So ... I would like to perform the same fit as TB has done in this [paper](http://iopscience.iop.org/1748-0221/9/10/P10012/pdf/1748-0221_9_10_P10012.pdf)
in formula 5.2 & 5.3
And then by looking at the result of the fit, decide if the shifter needs to be called or not, in order to schedule another ratescan, or if the ratescan is just fine.

What's more, I think those fits should be done for all ratescans ever taken and the results should be put into a Database (Not RunInfo, since ratescans are not runs, but similar)
In order to be able, to monitor plots like fig. 13 & fig 14.
Because when we see systematic changes in these plots, maybe we learn something about ageing mirrors or whatever.... 

So instead of letting the shift_helper do the fitting of the ratescan, I would ask the collaboration, if they want these ratescan-fit-results in the database, and then let the shift_helper access that DB, in order to assess the quality of the last ratscan.

----

For now however, I would propose the shifter sets her alarm clock to the time of the ratescan and directly looks at the plot.

----------------------------------------
- Bitbucket: https://bitbucket.org/dneise/fact_shift_helper/issue/9

**Comment by dneise** [comment]
Ratescand are not taken anymore
