### ISSUE TITLE
Implement new checks that should result in a call to the shifter

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#91]
- [x] Trigger rate lower than 1 / s for longer than 10 Minutes 
  * Running Average? Running Maximum?
- [x] Bias not operating during data run
- [x] BIAS channels in OverCurrent
- [x] BIAS voltage not at reference
- [x] Container temperature > 42°C
- [x] Outside humidity exceeds 98% while lid is open
- [x] DIM network not available
- [x] no dimctrl server available
- [x] Drive in ERROR state during data-run
- [x] Bias voltage switched on, but bias crate not calibrated
- [x] wind gusts during tracking

**Comment by dneise** [comment]
Done in PR #107
