### ISSUE TITLE
local replica of DB

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#97]
shifthelper needs always access to DB, so we create a local replica of selected parts (if not all) of our mysql DB on lapalma.

**Comment by dneise** [comment]
we thought about replicating into a local sqlite3 DB, but this create synchronization issues, so we go for a normal mysql DB.

**Comment by dneise** [comment]
we could use mysql intrinsic replication or roll out our own:
 - every 30 minutes ... read entire remote DB and push it into our local replica.

not sure what is better

**Comment by dneise** [comment]
Working on this .... have a look at #113

**Comment by MaxNoe** [comment]
As it propably runs in the same Computer AS the Webinterface we could use the same mysql db

**Comment by dneise** [comment]
It is using the same db, but you can't know this because stupid me forgot to push the new config file. Sorry

**Comment by dneise** [comment]
working now
